name: Android Download Artifact

on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

jobs:
  download_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact
          path: app

      - name: Display Contents
        run: ls -R app
