name: Android CI

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main
      - ci-cd

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Use AdoptOpenJDK distribution for setting up Java environment
        cache: gradle # Cache the Gradle dependencies to improve build performance

    - name: Display current directory
      run: pwd

    - name: Grant execute permissions to scripts
      run: |
        chmod +x ./ci/build.sh
        chmod +x ./ci/run_tests.sh

    - name: Build and Test
      run: |
        ./ci/build.sh
        ./ci/run_tests.sh